# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.17.0-alpha.7

# Dependencies
fabric_version=0.146.1+26.1.2
modmenu_version=18.0.0-alpha.8
junit_version=6.0.3

# Mod Properties
mod_version=1.0.0
maven_group=com.dd3ok
archives_base_name=fpsxyzs
